### ISSUE TITLE
WebKit-compatible ligatures

### ISSUE THREAD

**Issue by wasokeli** [kreativekorp/sitelen-seli-kiwen#14]
WebKit has a bug where a ligature of the form `p o n a space` will be correctly replaced[^1], but the space will then be rendered again. This affects every iOS browser, as well as Safari for macOS.

mun.la was affected by this when it used SSK, and sona.pona.la is currently being affected by it. This also affected Sonja when she tested SSK for a page of hers.

![image](https://github.com/user-attachments/assets/aad9d86b-1400-4942-a4fc-c14d72942b33)

As far as anyone has been able to determine, the only workarounds are:
1. Avoid putting spaces between words, by using UCSUR text, orbytypinglikethis.
2. Author a font such that the `space` character is zero-width, and spaces can be inserted some other way, like U+3000 ideographic space, or `space space` or `z z` ligatures.

It would be nice to have a ligature version of SSK that works around this Safari bug, with method 2, for use on web pages.

[^1]: I tested it with a custom font; the `p o n a space` ligature is being used, not the `p o n a` one.

**Comment by RebeccaRGB** [comment]
This isn't really the right way to do things, but I don't expect Apple to fix their shit any time soon. Reluctantly implemented in 1.8.
